server:
  port: 8091
spring:
  rabbitmq:
    host: yangfan.cloud
    port: 5672
    username: guest
    password: guest
    virtual-host: my_vhost
    listener:
      simple:
#        分发原则 0 轮询分发模式
        prefetch: 0