#   配置文件中，指定程序名user-service，端口号8762，
#  服务注册地址http://localhost:8761/eureka/，Zipkin Server地址http://localhost:9411。
#  Spring Cloud Sleuth 有一个 Sampler 策略，可以通过这个实现类来控制采样算法。采样器不会阻碍 span 相关 id 的产生，
#  但是会对导出以及附加事件标签的相关操作造成影响。 Sleuth 默认采样算法的实现是 Reservoir sampling，
#  具体的实现类是 PercentageBasedSampler，默认的采样比例为: 0.1(即 10%)。
#   不过我们可以通过spring.sleuth.sampler.probability来设置，
#   所设置的值介于 0.0 到 1.0 之间，1.0 则表示全部采集。


server:
  port: 8763
spring:
  application:
    name: user-service
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411 # 指定了 Zipkin 服务器的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
