server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    #打开注释，则通过【http://localhost/dp-lte】访问
    #context-path: /dp-lte
spring:
    redis:
        database: 0
        host: 106.12.101.177
        port: 6379
        password:     # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        jedis:
          pool:
              max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 10      # 连接池中的最大空闲连接
              min-idle: 5       # 连接池中的最小空闲连接

