# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    #打开注释，则通过【http://localhost/dp-lte】访问
    #context-path: /dp-lte

spring:
    # 环境 dev:开发环境|test:测试环境|prod:生成环境
    profiles:
        active: prod
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # thymeleaf 模板引擎
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        content-type: text/html
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

