spring:
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
#        password: root
        timeout: 6000  # 连接超时时长（毫秒）
        cluster:
            nodes: 192.168.7.28:7000,192.168.7.28:7001,192.168.7.28:7002
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 1       # 连接池中的最小空闲连接

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
#            masterDataSource:  #主库数据源
#              url: jdbc:mysql://localhost:3306/yfzero?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#              username: root
#              password: 123456
#            slaveDataSource:  #从库数据源
#              url: jdbc:mysql://localhost:3306/yfzero?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#              username: root
#              password: 123456

            url: jdbc:mysql://47.104.219.199:3306/yfzero?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
            username: root
            password: uAiqwVwjJ8-i

            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: sys
                login-password: sys
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true


