#热部署生效
spring.devtools.restart.enabled: true
spring.session.store-type: redis
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8089
    #打开注释，则通过【http://localhost/dp-lte】访问
    #context-path: /dp-lte

spring:
    # 环境 dev:开发环境|test:测试环境|prod:生成环境
    profiles:
        active: dev
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # thymeleaf 模板引擎
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/

    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
#        password: root
        timeout: 6000  # 连接超时时长（毫秒）
        cluster:
            nodes: 192.168.7.28:7000,192.168.7.28:7001,192.168.7.28:7002
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 1       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml

