
server:
    port: 8081

#应用名称
spring:
    dubbo:
          application:
              name: dubbo-provider # 本服务的名称
          registry:
              address: zookeeper://127.0.0.1:2181 # ZooKeeper所在服务器的IP和端口号
          protocol:
              name: dubbo # RPC通信所采用的协议
              port: 20880 # 本服务对外暴露的端口号
          scan: com.yf.dubbo.provide.service # 服务实现类所在的路径
          provider:
              retries: 0  # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试