
server:
    port: 8081
spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.yf.dubbo.provide.service  # dubbo服务发布者实现类注解@service所在的包
    registry:
      address: 127.0.0.1                # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试

